gnes-commit-lint-pipe: &bp0
  docker:
    image: node:alpine
  stages:
    - name: do commit lint
      script:
        - npm install --global --save-dev @commitlint/config-conventional @commitlint/cli --registry=http://r.tnpm.oa.com
        - "echo \"module.exports = {extends: ['@commitlint/config-conventional']}\" > commitlint.config.js"
        - echo $DRONE_COMMIT_MESSAGE | commitlint

install-deps: &install_deps
  - name: install dependencies
    jobs:
      - name: setup ci environment
        script:
          - mkdir -p .cache && ln -snf $(pwd)/.cache $HOME/.cache
          - export PIP_DOWNLOAD_CACHE=${pwd}/.cache/pip_download_cache && export XDG_CACHE_HOME=${pwd}/.cache/pip
          - printf "XDG_CACHE_HOME=$XDG_CACHE_HOME\nPIP_DOWNLOAD_CACHE=$PIP_DOWNLOAD_CACHE\n"
          - cat /proc/cpuinfo | grep flags
          - "python -c 'import tensorflow as tf; print(tf.__version__); a=tf.constant(1, tf.int32); print(tf.Session().run(a))'"
          - nvcc --version
      - name: install project deps
        env:
          INDEX_URL: http://mirrors.oa.com/pypi/web/simple/
          TRUST_DOM: mirrors.oa.com
        script:
          - pip install cffi==1.12.3
          - "pip install -e .[all] -i ${INDEX_URL} --extra-index-url ${INDEX_URL} --trusted-host ${TRUST_DOM}"
          - pip uninstall -y torchvision
          - pip install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
          - "python -c 'import torchvision; print(torchvision.__version__)'"
          - "python -c 'import torch; print(torch.__version__)'"
          - python -m unittest tests/*.py -v

pylint: &pylint
  - name: check code style
    script: pylint gnes/**/*.py --exit-zero

unit-test: &unit_test
  - name: run unit test
    script: python -m unittest tests/*.py

notify-stage: &notify_stage
  - name: git comment
    jobs:
      - name: make comment
        script: echo "🍊 looks good to me 👍" > comment.txt
      - name: submit comment
        type: git:comment
        options:
          fromFile: comment.txt
      - name: make notification
        script: echo "$SUCCESS_MSG" > notify.md
      - name: message
        type: wework:message
        options:
          robot: f5ee526b-c6dc-4ef1-97c0-ac14594e57b0
          fromFile: notify.md


gnes-unit-test-pipe: &bp1
  network: idc-ai-sse4
  docker:
    image: gnes/ci-base
  env:
    GNES_ENV_SET: orange-ci
    PIP_DOWNLOAD_CACHE: ${pwd}/.cache/pip_download_cache
    XDG_CACHE_HOME: ${pwd}/.cache/pip
    SUCCESS_MSG: "# ✅😃 All tests passed, good job! \n由$ORANGE_BUILD_USER提交的$ORANGE_MERGE_REQUEST_BRANCH分支刚刚测试通过！\n[点击查看]($ORANGE_EVENT_URL)"
  cacheFrom: .orange-ci.cache
  stages:
    - <<: *install_deps
    - <<: *pylint
    - <<: *unit_test
    - <<: *notify_stage

notify-pipeline1: &np1
  network: devnet
  stages:
    - name: make notification
      script: echo "# 🚀 NES的Master分支刚刚更新了！\n此次更新由$ORANGE_BUILD_USER提交的$ORANGE_MERGE_REQUEST_BRANCH合并后触发，[点击查看](https://git.code.oa.com/ai-innersource/nes/)" > notify.md
    - name: send mail
      type: mail:send
      options:
        title: 🚀 NES的Master分支刚刚更新！
        to:
          - hanhxiao
          - larryjfyan
          - madwang
          - leonjiang
          - raccoonliu
          - kegokang
        type: markdown
        fromFile: notify.md
    - name: message
      type: wework:message
      options:
        robot: f5ee526b-c6dc-4ef1-97c0-ac14594e57b0
        fromFile: notify.md

docker-stage: &docker_stage
  - name: docker push
    jobs:
      - name: docker login
        script: docker login -u $DOCKER_USER -p $DOCKER_PWD docker.oa.com:8080
      - name: push docker
        script: export DOCKER_NAMESPACE="docker.oa.com:8080/public" && bash docker-push.sh $GIT_TAG
      - name: make notification
        script: export DOCKER_NAMESPACE="docker.oa.com:8080/public" && echo "# 🗳️ NES容器的$GIT_TAG版本刚刚更新至$DOCKER_NAMESPACE！\n运行此版本：\ndocker pull $DOCKER_NAMESPACE/$PROJ_NAME:$GIT_TAG && docker run -v /data1/cips/data:/ext_data -it $DOCKER_NAMESPACE/$PROJ_NAME:$GIT_TAG bash" >>notify.md
      - name: docker login
        script: docker login -u $TCLOUD_USER -p $TCLOUD_PWD ccr.ccs.tencentyun.com
      - name: push docker
        script: export DOCKER_NAMESPACE="ccr.ccs.tencentyun.com/gnes" && bash docker-push.sh $GIT_TAG
      - name: make notification
        script: export DOCKER_NAMESPACE="ccr.ccs.tencentyun.com/gnes" && echo "# 🗳️ NES容器的$GIT_TAG版本刚刚更新至$DOCKER_NAMESPACE！\n运行此版本：\ndocker pull $DOCKER_NAMESPACE/$PROJ_NAME:$GIT_TAG && docker run -v /data1/cips/data:/ext_data -it $DOCKER_NAMESPACE/$PROJ_NAME:$GIT_TAG bash" >> notify.md

release-stage: &release_stage1
  - name: notify about release
    jobs:
      - name: send mail
        type: mail:send
        options:
          title: 🗳️ NES容器的$GIT_TAG刚刚更新！
          to:
            - hanhxiao
            - larryjfyan
            - madwang
          type: markdown
          fromFile: notify.md
      - name: message
        type: wework:message
        options:
          robot: f5ee526b-c6dc-4ef1-97c0-ac14594e57b0
          fromFile: notify.md

release-stage2: &release_stage2
  - name: notify about release
    jobs:
      - name: send mail
        type: mail:send
        options:
          title: 🗳️ NES容器的$GIT_TAG刚刚更新！
          to:
            - g_AIPD_SC_RELEVANCE
          type: markdown
          fromFile: notify.md
      - name: message
        type: wework:message
        options:
          robot: 33f48450-4e17-4e99-b476-b1c97ea233c6
          fromFile: notify.md

docker-pipeline1: &dp1
  network: devnet
  services:
    - docker
  envFrom: https://git.code.oa.com/hanhxiao/nes-keys/blob/master/env
  env:
    PROJ_NAME: aipd-gnes
    GIT_TAG: master
  stages:
    - <<: *docker_stage
    - <<: *release_stage1

docker-pipeline2: &dp2
  network: devnet
  services:
    - docker
  envFrom: https://git.code.oa.com/hanhxiao/nes-keys/blob/master/env
  env:
    PROJ_NAME: aipd-gnes
    GIT_TAG: $ORANGE_BRANCH
  stages:
    - <<: *docker_stage
    - <<: *release_stage2

master:
  merge_request:
    - <<: *bp0
    - <<: *bp1
  push:
    - <<: *np1
    - <<: *dp1

"**":
  tag_push:
    - <<: *dp2